name: publish-sdks

on:
  workflow_dispatch:

jobs:
  publish-scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show version
        run: cat VERSION
      - name: Show python package manifest
        run: cat sdk-python/pyproject.toml
      - name: Show js package manifest
        run: cat sdk-js/package.json
