name: release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show version
        run: cat VERSION
      - name: Show changelog
        run: cat CHANGELOG.md
